# Generated by Django 5.2.3 on 2025-07-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_subscription_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
