name: 1-Hello github actions

on:
  #workflow_dispatch:
  #schedule: 
  #  - cron: '30 15 * * *'
  #push: # push github
  #  branch:
  #    -main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello there
        run: echo "hello"