name: 1-Hello github actions

on:
  workflow_dispatch:
  push: # push github
    branch:
      -main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello there
        run: echo "hello"