name: 2-DjangoBasis

on:
  workflow_dispatch:
  push: # push github
    branch:
      -main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Pipenv # Paso para instalar Pipenv
        run: |
          python -m pip install pipenv

      - name: Install dependencies with Pipenv 
        run: pipenv install --dev

      - name: Django tests
        working-directory: ./app
        env: 
          DJANGO_SECRET_KEY: not-good
        run: |
          pipenv run python manage.py test
          