name: 2-DjangoBasis

on:
  workflow_dispatch:
  push: # push github
    branch:
      -main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: 0
      #DJANGO_SECRET_KEY:
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Django Secret Key
        run: |
          MY_GEN_KEY=$(openssl rand -base64 32)
          echo "DJANGO_SECRET_KEY=$MY_GEN_KEY" >> $GITHUB_ENV
      - name: Install Pipenv # Paso para instalar Pipenv
        run: |
          python -m pip install pipenv

      - name: Install dependencies with Pipenv 
        run: pipenv install --dev
      - name: Django tests
        working-directory: ./app
        run: |
          pipenv run python manage.py test
          